version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: my-clickhouse-server
    volumes:
      - /var/lib/clickhouse/:/var/lib/clickhouse/
      - /var/log/clickhouse-server/:/var/log/clickhouse-server/
    ports:
      - "8123:8123"
      - "7000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
