
services:
  redis:
    image: redis:6
    container_name: redis
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.12
      - REDIS_VERSION=6.0.5
      - REDIS_DOWNLOAD_URL=https://download.redis.io/releases/redis-5.0.14.tar.gz
      - REDIS_DOWNLOAD_SHA=42cf86a114d2a451b898fcda96acd4d01062a7dbaaad2801d9164a36f898f596
    volumes:
      - redis_data:/data
      - /data:/data
    working_dir: /data
    ports:
      - "127.0.0.1:6379:6379"
      - "10.206.16.2:6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--bind", "0.0.0.0", "--dir", "/data", "--dbfilename", "dump.rdb", "--appendonly", "yes", "--appendfilename", "appendonly.aof", "--appendfsync", "everysec"]

volumes:
  redis_data:
